<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>Kayori.Medusa.Abstractions</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AssetsTools.NET" Version="3.0.5" />
        <PackageReference Include="AssetsTools.NET.Texture" Version="3.0.2" />
        <PackageReference Include="SkiaSharp" Version="4.151.0" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.151.0" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
