/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/forgotPassword/': RouteRecordInfo<
      '/auth/forgotPassword/',
      '/auth/forgotPassword',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/forgotPassword/confirmation': RouteRecordInfo<
      '/auth/forgotPassword/confirmation',
      '/auth/forgotPassword/confirmation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/register': RouteRecordInfo<
      '/auth/register',
      '/auth/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/resetPassword/': RouteRecordInfo<
      '/auth/resetPassword/',
      '/auth/resetPassword',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/resetPassword/confirmation': RouteRecordInfo<
      '/auth/resetPassword/confirmation',
      '/auth/resetPassword/confirmation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cardless/[token]': RouteRecordInfo<
      '/cardless/[token]',
      '/cardless/:token',
      { token: ParamValue<true> },
      { token: ParamValue<false> },
      | never
    >,
    '/cardless/scan': RouteRecordInfo<
      '/cardless/scan',
      '/cardless/scan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cards/': RouteRecordInfo<
      '/cards/',
      '/cards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/forgotPassword/index.vue': {
      routes:
        | '/auth/forgotPassword/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/forgotPassword/confirmation.vue': {
      routes:
        | '/auth/forgotPassword/confirmation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/register.vue': {
      routes:
        | '/auth/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/resetPassword/index.vue': {
      routes:
        | '/auth/resetPassword/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/resetPassword/confirmation.vue': {
      routes:
        | '/auth/resetPassword/confirmation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/cardless/[token].vue': {
      routes:
        | '/cardless/[token]'
      views:
        | never
      pathParamNames:
        | 'token'
    }
    'src/pages/cardless/scan.vue': {
      routes:
        | '/cardless/scan'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/cards/index.vue': {
      routes:
        | '/cards/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
