/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Server | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  toValue,
  unref
} from 'vue';
import type {
  MaybeRefOrGetter
} from 'vue';

import type {
  AccessTokenResponse,
  ApproveSessionResponse,
  CardDto,
  Claim,
  ForgotPasswordRequest,
  HttpValidationProblemDetails,
  InfoRequest,
  InfoResponse,
  LoginRequest,
  MapIdentityApiApiAuthConfirmEmailParams,
  PinResponse,
  PluginUiManifestResponse,
  PostApiAuthLoginParams,
  PostEamuseMParams,
  PostEamuseParams,
  RefreshRequest,
  RegisterRequest,
  ResendConfirmationEmailRequest,
  ResetPasswordRequest,
  TwoFactorRequest,
  TwoFactorResponse,
  UpdatePinRequest,
  UpdateUsernameRequest,
  ValidateCardRequest,
  ValidateCardResponse
} from '../types/api';

import { customFetch } from './customFetch';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getPluginAssetsPluginUiIdFilePathResponse200 = {
  data: void
  status: 200
}

export type getPluginAssetsPluginUiIdFilePathResponseSuccess = (getPluginAssetsPluginUiIdFilePathResponse200) & {
  headers: Headers;
};
;

export type getPluginAssetsPluginUiIdFilePathResponse = (getPluginAssetsPluginUiIdFilePathResponseSuccess)

export const getGetPluginAssetsPluginUiIdFilePathUrl = (pluginUiId: string,
    filePath: string,) => {




  return `/pluginAssets/${pluginUiId}/${filePath}`
}

export const getPluginAssetsPluginUiIdFilePath = async (pluginUiId: string,
    filePath: string, options?: Parameters<typeof customFetch>[1]): Promise<getPluginAssetsPluginUiIdFilePathResponse> => {

  return customFetch<getPluginAssetsPluginUiIdFilePathResponse>(getGetPluginAssetsPluginUiIdFilePathUrl(pluginUiId,filePath),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPluginAssetsPluginUiIdFilePathQueryKey = (pluginUiId: MaybeRefOrGetter<string>,
    filePath: MaybeRefOrGetter<string>,) => {
    return [
    'pluginAssets',pluginUiId,filePath
    ] as const;
    }


export const getGetPluginAssetsPluginUiIdFilePathQueryOptions = <TData = Awaited<ReturnType<typeof getPluginAssetsPluginUiIdFilePath>>, TError = unknown>(pluginUiId: MaybeRefOrGetter<string>,
    filePath: MaybeRefOrGetter<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginAssetsPluginUiIdFilePath>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetPluginAssetsPluginUiIdFilePathQueryKey(pluginUiId,filePath);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPluginAssetsPluginUiIdFilePath>>> = ({ signal }) => getPluginAssetsPluginUiIdFilePath(toValue(pluginUiId),toValue(filePath), { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: computed(() => toValue(pluginUiId) !== null && toValue(pluginUiId) !== undefined && toValue(filePath) !== null && toValue(filePath) !== undefined), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPluginAssetsPluginUiIdFilePath>>, TError, TData>
}

export type GetPluginAssetsPluginUiIdFilePathQueryResult = NonNullable<Awaited<ReturnType<typeof getPluginAssetsPluginUiIdFilePath>>>
export type GetPluginAssetsPluginUiIdFilePathQueryError = unknown



export function useGetPluginAssetsPluginUiIdFilePath<TData = Awaited<ReturnType<typeof getPluginAssetsPluginUiIdFilePath>>, TError = unknown>(
 pluginUiId: MaybeRefOrGetter<string>,
    filePath: MaybeRefOrGetter<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginAssetsPluginUiIdFilePath>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPluginAssetsPluginUiIdFilePathQueryOptions(pluginUiId,filePath,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type postApiCardsValidateResponse200 = {
  data: ValidateCardResponse
  status: 200
}

export type postApiCardsValidateResponseSuccess = (postApiCardsValidateResponse200) & {
  headers: Headers;
};
;

export type postApiCardsValidateResponse = (postApiCardsValidateResponseSuccess)

export const getPostApiCardsValidateUrl = () => {




  return `/api/cards/validate`
}

export const postApiCardsValidate = async (validateCardRequest: ValidateCardRequest, options?: Parameters<typeof customFetch>[1]): Promise<postApiCardsValidateResponse> => {

  return customFetch<postApiCardsValidateResponse>(getPostApiCardsValidateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(validateCardRequest)
  }
);}





export const getPostApiCardsValidateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCardsValidate>>, TError,{data: ValidateCardRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiCardsValidate>>, TError,{data: ValidateCardRequest}, TContext> => {

const mutationKey = ['postApiCardsValidate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCardsValidate>>, {data: ValidateCardRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiCardsValidate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiCardsValidateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCardsValidate>>>
    export type PostApiCardsValidateMutationBody = ValidateCardRequest
    export type PostApiCardsValidateMutationError = unknown

    export const usePostApiCardsValidate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCardsValidate>>, TError,{data: ValidateCardRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiCardsValidate>>,
        TError,
        {data: ValidateCardRequest},
        TContext
      > => {
      return useMutation(getPostApiCardsValidateMutationOptions(options), queryClient);
    }

export type getApiCardsMyResponse200 = {
  data: CardDto[]
  status: 200
}

export type getApiCardsMyResponseSuccess = (getApiCardsMyResponse200) & {
  headers: Headers;
};
;

export type getApiCardsMyResponse = (getApiCardsMyResponseSuccess)

export const getGetApiCardsMyUrl = () => {




  return `/api/cards/my`
}

export const getApiCardsMy = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiCardsMyResponse> => {

  return customFetch<getApiCardsMyResponse>(getGetApiCardsMyUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiCardsMyQueryKey = () => {
    return [
    'api','cards','my'
    ] as const;
    }


export const getGetApiCardsMyQueryOptions = <TData = Awaited<ReturnType<typeof getApiCardsMy>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCardsMy>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetApiCardsMyQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCardsMy>>> = ({ signal }) => getApiCardsMy({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCardsMy>>, TError, TData>
}

export type GetApiCardsMyQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCardsMy>>>
export type GetApiCardsMyQueryError = unknown



export function useGetApiCardsMy<TData = Awaited<ReturnType<typeof getApiCardsMy>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCardsMy>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCardsMyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type getApiUserClaimsResponse200 = {
  data: Claim[]
  status: 200
}

export type getApiUserClaimsResponseSuccess = (getApiUserClaimsResponse200) & {
  headers: Headers;
};
;

export type getApiUserClaimsResponse = (getApiUserClaimsResponseSuccess)

export const getGetApiUserClaimsUrl = () => {




  return `/api/user/claims`
}

export const getApiUserClaims = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiUserClaimsResponse> => {

  return customFetch<getApiUserClaimsResponse>(getGetApiUserClaimsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiUserClaimsQueryKey = () => {
    return [
    'api','user','claims'
    ] as const;
    }


export const getGetApiUserClaimsQueryOptions = <TData = Awaited<ReturnType<typeof getApiUserClaims>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserClaims>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetApiUserClaimsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUserClaims>>> = ({ signal }) => getApiUserClaims({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUserClaims>>, TError, TData>
}

export type GetApiUserClaimsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUserClaims>>>
export type GetApiUserClaimsQueryError = unknown



export function useGetApiUserClaims<TData = Awaited<ReturnType<typeof getApiUserClaims>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserClaims>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUserClaimsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type postApiCardlessTokenApproveResponse200 = {
  data: ApproveSessionResponse
  status: 200
}

export type postApiCardlessTokenApproveResponse400 = {
  data: ApproveSessionResponse
  status: 400
}

export type postApiCardlessTokenApproveResponse404 = {
  data: ApproveSessionResponse
  status: 404
}

export type postApiCardlessTokenApproveResponseSuccess = (postApiCardlessTokenApproveResponse200) & {
  headers: Headers;
};
export type postApiCardlessTokenApproveResponseError = (postApiCardlessTokenApproveResponse400 | postApiCardlessTokenApproveResponse404) & {
  headers: Headers;
};

export type postApiCardlessTokenApproveResponse = (postApiCardlessTokenApproveResponseSuccess | postApiCardlessTokenApproveResponseError)

export const getPostApiCardlessTokenApproveUrl = (token: string,) => {




  return `/api/cardless/${token}/approve`
}

export const postApiCardlessTokenApprove = async (token: string, options?: Parameters<typeof customFetch>[1]): Promise<postApiCardlessTokenApproveResponse> => {

  return customFetch<postApiCardlessTokenApproveResponse>(getPostApiCardlessTokenApproveUrl(token),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostApiCardlessTokenApproveMutationOptions = <TError = ApproveSessionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCardlessTokenApprove>>, TError,{token: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiCardlessTokenApprove>>, TError,{token: string}, TContext> => {

const mutationKey = ['postApiCardlessTokenApprove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCardlessTokenApprove>>, {token: string}> = (props) => {
          const {token} = props ?? {};

          return  postApiCardlessTokenApprove(token,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiCardlessTokenApproveMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCardlessTokenApprove>>>

    export type PostApiCardlessTokenApproveMutationError = ApproveSessionResponse

    export const usePostApiCardlessTokenApprove = <TError = ApproveSessionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCardlessTokenApprove>>, TError,{token: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiCardlessTokenApprove>>,
        TError,
        {token: string},
        TContext
      > => {
      return useMutation(getPostApiCardlessTokenApproveMutationOptions(options), queryClient);
    }

export type postApiAuthRegisterResponse200 = {
  data: void
  status: 200
}

export type postApiAuthRegisterResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiAuthRegisterResponseSuccess = (postApiAuthRegisterResponse200) & {
  headers: Headers;
};
export type postApiAuthRegisterResponseError = (postApiAuthRegisterResponse400) & {
  headers: Headers;
};

export type postApiAuthRegisterResponse = (postApiAuthRegisterResponseSuccess | postApiAuthRegisterResponseError)

export const getPostApiAuthRegisterUrl = () => {




  return `/api/auth/register`
}

export const postApiAuthRegister = async (registerRequest: RegisterRequest, options?: Parameters<typeof customFetch>[1]): Promise<postApiAuthRegisterResponse> => {

  return customFetch<postApiAuthRegisterResponse>(getPostApiAuthRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerRequest)
  }
);}





export const getPostApiAuthRegisterMutationOptions = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data: RegisterRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['postApiAuthRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRegister>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRegister(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRegister>>>
    export type PostApiAuthRegisterMutationBody = RegisterRequest
    export type PostApiAuthRegisterMutationError = HttpValidationProblemDetails

    export const usePostApiAuthRegister = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data: RegisterRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthRegister>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthRegisterMutationOptions(options), queryClient);
    }

export type postApiAuthLoginResponse200 = {
  data: AccessTokenResponse
  status: 200
}

export type postApiAuthLoginResponseSuccess = (postApiAuthLoginResponse200) & {
  headers: Headers;
};
;

export type postApiAuthLoginResponse = (postApiAuthLoginResponseSuccess)

export const getPostApiAuthLoginUrl = (params?: PostApiAuthLoginParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/login?${stringifiedParams}` : `/api/auth/login`
}

export const postApiAuthLogin = async (loginRequest: LoginRequest,
    params?: PostApiAuthLoginParams, options?: Parameters<typeof customFetch>[1]): Promise<postApiAuthLoginResponse> => {

  return customFetch<postApiAuthLoginResponse>(getPostApiAuthLoginUrl(params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginRequest)
  }
);}





export const getPostApiAuthLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: LoginRequest;params?: PostApiAuthLoginParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: LoginRequest;params?: PostApiAuthLoginParams}, TContext> => {

const mutationKey = ['postApiAuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthLogin>>, {data: LoginRequest;params?: PostApiAuthLoginParams}> = (props) => {
          const {data,params} = props ?? {};

          return  postApiAuthLogin(data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogin>>>
    export type PostApiAuthLoginMutationBody = LoginRequest
    export type PostApiAuthLoginMutationError = unknown

    export const usePostApiAuthLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: LoginRequest;params?: PostApiAuthLoginParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthLogin>>,
        TError,
        {data: LoginRequest;params?: PostApiAuthLoginParams},
        TContext
      > => {
      return useMutation(getPostApiAuthLoginMutationOptions(options), queryClient);
    }

export type postApiAuthRefreshResponse200 = {
  data: AccessTokenResponse
  status: 200
}

export type postApiAuthRefreshResponseSuccess = (postApiAuthRefreshResponse200) & {
  headers: Headers;
};
;

export type postApiAuthRefreshResponse = (postApiAuthRefreshResponseSuccess)

export const getPostApiAuthRefreshUrl = () => {




  return `/api/auth/refresh`
}

export const postApiAuthRefresh = async (refreshRequest: RefreshRequest, options?: Parameters<typeof customFetch>[1]): Promise<postApiAuthRefreshResponse> => {

  return customFetch<postApiAuthRefreshResponse>(getPostApiAuthRefreshUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(refreshRequest)
  }
);}





export const getPostApiAuthRefreshMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,{data: RefreshRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,{data: RefreshRequest}, TContext> => {

const mutationKey = ['postApiAuthRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRefresh>>, {data: RefreshRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRefresh(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRefresh>>>
    export type PostApiAuthRefreshMutationBody = RefreshRequest
    export type PostApiAuthRefreshMutationError = unknown

    export const usePostApiAuthRefresh = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,{data: RefreshRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthRefresh>>,
        TError,
        {data: RefreshRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthRefreshMutationOptions(options), queryClient);
    }

export type mapIdentityApiApiAuthConfirmEmailResponse200 = {
  data: void
  status: 200
}

export type mapIdentityApiApiAuthConfirmEmailResponseSuccess = (mapIdentityApiApiAuthConfirmEmailResponse200) & {
  headers: Headers;
};
;

export type mapIdentityApiApiAuthConfirmEmailResponse = (mapIdentityApiApiAuthConfirmEmailResponseSuccess)

export const getMapIdentityApiApiAuthConfirmEmailUrl = (params: MapIdentityApiApiAuthConfirmEmailParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/confirmEmail?${stringifiedParams}` : `/api/auth/confirmEmail`
}

export const mapIdentityApiApiAuthConfirmEmail = async (params: MapIdentityApiApiAuthConfirmEmailParams, options?: Parameters<typeof customFetch>[1]): Promise<mapIdentityApiApiAuthConfirmEmailResponse> => {

  return customFetch<mapIdentityApiApiAuthConfirmEmailResponse>(getMapIdentityApiApiAuthConfirmEmailUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getMapIdentityApiApiAuthConfirmEmailQueryKey = (params?: MaybeRefOrGetter<MapIdentityApiApiAuthConfirmEmailParams>,) => {
    return [
    'api','auth','confirmEmail', ...(params ? [params] : [])
    ] as const;
    }


export const getMapIdentityApiApiAuthConfirmEmailQueryOptions = <TData = Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>, TError = unknown>(params: MaybeRefOrGetter<MapIdentityApiApiAuthConfirmEmailParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getMapIdentityApiApiAuthConfirmEmailQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>> = ({ signal }) => mapIdentityApiApiAuthConfirmEmail(toValue(params), { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>, TError, TData>
}

export type MapIdentityApiApiAuthConfirmEmailQueryResult = NonNullable<Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>>
export type MapIdentityApiApiAuthConfirmEmailQueryError = unknown



export function useMapIdentityApiApiAuthConfirmEmail<TData = Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>, TError = unknown>(
 params: MaybeRefOrGetter<MapIdentityApiApiAuthConfirmEmailParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMapIdentityApiApiAuthConfirmEmailQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type postApiAuthResendConfirmationEmailResponse200 = {
  data: void
  status: 200
}

export type postApiAuthResendConfirmationEmailResponseSuccess = (postApiAuthResendConfirmationEmailResponse200) & {
  headers: Headers;
};
;

export type postApiAuthResendConfirmationEmailResponse = (postApiAuthResendConfirmationEmailResponseSuccess)

export const getPostApiAuthResendConfirmationEmailUrl = () => {




  return `/api/auth/resendConfirmationEmail`
}

export const postApiAuthResendConfirmationEmail = async (resendConfirmationEmailRequest: ResendConfirmationEmailRequest, options?: Parameters<typeof customFetch>[1]): Promise<postApiAuthResendConfirmationEmailResponse> => {

  return customFetch<postApiAuthResendConfirmationEmailResponse>(getPostApiAuthResendConfirmationEmailUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(resendConfirmationEmailRequest)
  }
);}





export const getPostApiAuthResendConfirmationEmailMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>, TError,{data: ResendConfirmationEmailRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>, TError,{data: ResendConfirmationEmailRequest}, TContext> => {

const mutationKey = ['postApiAuthResendConfirmationEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>, {data: ResendConfirmationEmailRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthResendConfirmationEmail(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthResendConfirmationEmailMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>>
    export type PostApiAuthResendConfirmationEmailMutationBody = ResendConfirmationEmailRequest
    export type PostApiAuthResendConfirmationEmailMutationError = unknown

    export const usePostApiAuthResendConfirmationEmail = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>, TError,{data: ResendConfirmationEmailRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>,
        TError,
        {data: ResendConfirmationEmailRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthResendConfirmationEmailMutationOptions(options), queryClient);
    }

export type postApiAuthForgotPasswordResponse200 = {
  data: void
  status: 200
}

export type postApiAuthForgotPasswordResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiAuthForgotPasswordResponseSuccess = (postApiAuthForgotPasswordResponse200) & {
  headers: Headers;
};
export type postApiAuthForgotPasswordResponseError = (postApiAuthForgotPasswordResponse400) & {
  headers: Headers;
};

export type postApiAuthForgotPasswordResponse = (postApiAuthForgotPasswordResponseSuccess | postApiAuthForgotPasswordResponseError)

export const getPostApiAuthForgotPasswordUrl = () => {




  return `/api/auth/forgotPassword`
}

export const postApiAuthForgotPassword = async (forgotPasswordRequest: ForgotPasswordRequest, options?: Parameters<typeof customFetch>[1]): Promise<postApiAuthForgotPasswordResponse> => {

  return customFetch<postApiAuthForgotPasswordResponse>(getPostApiAuthForgotPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(forgotPasswordRequest)
  }
);}





export const getPostApiAuthForgotPasswordMutationOptions = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthForgotPassword>>, TError,{data: ForgotPasswordRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthForgotPassword>>, TError,{data: ForgotPasswordRequest}, TContext> => {

const mutationKey = ['postApiAuthForgotPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthForgotPassword>>, {data: ForgotPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthForgotPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthForgotPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthForgotPassword>>>
    export type PostApiAuthForgotPasswordMutationBody = ForgotPasswordRequest
    export type PostApiAuthForgotPasswordMutationError = HttpValidationProblemDetails

    export const usePostApiAuthForgotPassword = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthForgotPassword>>, TError,{data: ForgotPasswordRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthForgotPassword>>,
        TError,
        {data: ForgotPasswordRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthForgotPasswordMutationOptions(options), queryClient);
    }

export type postApiAuthResetPasswordResponse200 = {
  data: void
  status: 200
}

export type postApiAuthResetPasswordResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiAuthResetPasswordResponseSuccess = (postApiAuthResetPasswordResponse200) & {
  headers: Headers;
};
export type postApiAuthResetPasswordResponseError = (postApiAuthResetPasswordResponse400) & {
  headers: Headers;
};

export type postApiAuthResetPasswordResponse = (postApiAuthResetPasswordResponseSuccess | postApiAuthResetPasswordResponseError)

export const getPostApiAuthResetPasswordUrl = () => {




  return `/api/auth/resetPassword`
}

export const postApiAuthResetPassword = async (resetPasswordRequest: ResetPasswordRequest, options?: Parameters<typeof customFetch>[1]): Promise<postApiAuthResetPasswordResponse> => {

  return customFetch<postApiAuthResetPasswordResponse>(getPostApiAuthResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(resetPasswordRequest)
  }
);}





export const getPostApiAuthResetPasswordMutationOptions = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResetPassword>>, TError,{data: ResetPasswordRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResetPassword>>, TError,{data: ResetPasswordRequest}, TContext> => {

const mutationKey = ['postApiAuthResetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthResetPassword>>, {data: ResetPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthResetPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthResetPassword>>>
    export type PostApiAuthResetPasswordMutationBody = ResetPasswordRequest
    export type PostApiAuthResetPasswordMutationError = HttpValidationProblemDetails

    export const usePostApiAuthResetPassword = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResetPassword>>, TError,{data: ResetPasswordRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthResetPassword>>,
        TError,
        {data: ResetPasswordRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthResetPasswordMutationOptions(options), queryClient);
    }

export type postApiAuthManage2faResponse200 = {
  data: TwoFactorResponse
  status: 200
}

export type postApiAuthManage2faResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiAuthManage2faResponse404 = {
  data: void
  status: 404
}

export type postApiAuthManage2faResponseSuccess = (postApiAuthManage2faResponse200) & {
  headers: Headers;
};
export type postApiAuthManage2faResponseError = (postApiAuthManage2faResponse400 | postApiAuthManage2faResponse404) & {
  headers: Headers;
};

export type postApiAuthManage2faResponse = (postApiAuthManage2faResponseSuccess | postApiAuthManage2faResponseError)

export const getPostApiAuthManage2faUrl = () => {




  return `/api/auth/manage/2fa`
}

export const postApiAuthManage2fa = async (twoFactorRequest: TwoFactorRequest, options?: Parameters<typeof customFetch>[1]): Promise<postApiAuthManage2faResponse> => {

  return customFetch<postApiAuthManage2faResponse>(getPostApiAuthManage2faUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(twoFactorRequest)
  }
);}





export const getPostApiAuthManage2faMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManage2fa>>, TError,{data: TwoFactorRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManage2fa>>, TError,{data: TwoFactorRequest}, TContext> => {

const mutationKey = ['postApiAuthManage2fa'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthManage2fa>>, {data: TwoFactorRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthManage2fa(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthManage2faMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthManage2fa>>>
    export type PostApiAuthManage2faMutationBody = TwoFactorRequest
    export type PostApiAuthManage2faMutationError = HttpValidationProblemDetails | void

    export const usePostApiAuthManage2fa = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManage2fa>>, TError,{data: TwoFactorRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthManage2fa>>,
        TError,
        {data: TwoFactorRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthManage2faMutationOptions(options), queryClient);
    }

export type getApiAuthManageInfoResponse200 = {
  data: InfoResponse
  status: 200
}

export type getApiAuthManageInfoResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type getApiAuthManageInfoResponse404 = {
  data: void
  status: 404
}

export type getApiAuthManageInfoResponseSuccess = (getApiAuthManageInfoResponse200) & {
  headers: Headers;
};
export type getApiAuthManageInfoResponseError = (getApiAuthManageInfoResponse400 | getApiAuthManageInfoResponse404) & {
  headers: Headers;
};

export type getApiAuthManageInfoResponse = (getApiAuthManageInfoResponseSuccess | getApiAuthManageInfoResponseError)

export const getGetApiAuthManageInfoUrl = () => {




  return `/api/auth/manage/info`
}

export const getApiAuthManageInfo = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiAuthManageInfoResponse> => {

  return customFetch<getApiAuthManageInfoResponse>(getGetApiAuthManageInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAuthManageInfoQueryKey = () => {
    return [
    'api','auth','manage','info'
    ] as const;
    }


export const getGetApiAuthManageInfoQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthManageInfo>>, TError = HttpValidationProblemDetails | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthManageInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetApiAuthManageInfoQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthManageInfo>>> = ({ signal }) => getApiAuthManageInfo({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthManageInfo>>, TError, TData>
}

export type GetApiAuthManageInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthManageInfo>>>
export type GetApiAuthManageInfoQueryError = HttpValidationProblemDetails | void



export function useGetApiAuthManageInfo<TData = Awaited<ReturnType<typeof getApiAuthManageInfo>>, TError = HttpValidationProblemDetails | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthManageInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthManageInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type postApiAuthManageInfoResponse200 = {
  data: InfoResponse
  status: 200
}

export type postApiAuthManageInfoResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiAuthManageInfoResponse404 = {
  data: void
  status: 404
}

export type postApiAuthManageInfoResponseSuccess = (postApiAuthManageInfoResponse200) & {
  headers: Headers;
};
export type postApiAuthManageInfoResponseError = (postApiAuthManageInfoResponse400 | postApiAuthManageInfoResponse404) & {
  headers: Headers;
};

export type postApiAuthManageInfoResponse = (postApiAuthManageInfoResponseSuccess | postApiAuthManageInfoResponseError)

export const getPostApiAuthManageInfoUrl = () => {




  return `/api/auth/manage/info`
}

export const postApiAuthManageInfo = async (infoRequest: InfoRequest, options?: Parameters<typeof customFetch>[1]): Promise<postApiAuthManageInfoResponse> => {

  return customFetch<postApiAuthManageInfoResponse>(getPostApiAuthManageInfoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(infoRequest)
  }
);}





export const getPostApiAuthManageInfoMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManageInfo>>, TError,{data: InfoRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManageInfo>>, TError,{data: InfoRequest}, TContext> => {

const mutationKey = ['postApiAuthManageInfo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthManageInfo>>, {data: InfoRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthManageInfo(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthManageInfoMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthManageInfo>>>
    export type PostApiAuthManageInfoMutationBody = InfoRequest
    export type PostApiAuthManageInfoMutationError = HttpValidationProblemDetails | void

    export const usePostApiAuthManageInfo = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManageInfo>>, TError,{data: InfoRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthManageInfo>>,
        TError,
        {data: InfoRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthManageInfoMutationOptions(options), queryClient);
    }

export type postApiAuthManageUsernameResponse200 = {
  data: void
  status: 200
}

export type postApiAuthManageUsernameResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiAuthManageUsernameResponse404 = {
  data: void
  status: 404
}

export type postApiAuthManageUsernameResponseSuccess = (postApiAuthManageUsernameResponse200) & {
  headers: Headers;
};
export type postApiAuthManageUsernameResponseError = (postApiAuthManageUsernameResponse400 | postApiAuthManageUsernameResponse404) & {
  headers: Headers;
};

export type postApiAuthManageUsernameResponse = (postApiAuthManageUsernameResponseSuccess | postApiAuthManageUsernameResponseError)

export const getPostApiAuthManageUsernameUrl = () => {




  return `/api/auth/manage/username`
}

export const postApiAuthManageUsername = async (updateUsernameRequest: UpdateUsernameRequest, options?: Parameters<typeof customFetch>[1]): Promise<postApiAuthManageUsernameResponse> => {

  return customFetch<postApiAuthManageUsernameResponse>(getPostApiAuthManageUsernameUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateUsernameRequest)
  }
);}





export const getPostApiAuthManageUsernameMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManageUsername>>, TError,{data: UpdateUsernameRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManageUsername>>, TError,{data: UpdateUsernameRequest}, TContext> => {

const mutationKey = ['postApiAuthManageUsername'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthManageUsername>>, {data: UpdateUsernameRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthManageUsername(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthManageUsernameMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthManageUsername>>>
    export type PostApiAuthManageUsernameMutationBody = UpdateUsernameRequest
    export type PostApiAuthManageUsernameMutationError = HttpValidationProblemDetails | void

    export const usePostApiAuthManageUsername = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManageUsername>>, TError,{data: UpdateUsernameRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthManageUsername>>,
        TError,
        {data: UpdateUsernameRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthManageUsernameMutationOptions(options), queryClient);
    }

export type getApiAuthManagePinResponse200 = {
  data: PinResponse
  status: 200
}

export type getApiAuthManagePinResponse404 = {
  data: void
  status: 404
}

export type getApiAuthManagePinResponseSuccess = (getApiAuthManagePinResponse200) & {
  headers: Headers;
};
export type getApiAuthManagePinResponseError = (getApiAuthManagePinResponse404) & {
  headers: Headers;
};

export type getApiAuthManagePinResponse = (getApiAuthManagePinResponseSuccess | getApiAuthManagePinResponseError)

export const getGetApiAuthManagePinUrl = () => {




  return `/api/auth/manage/pin`
}

export const getApiAuthManagePin = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiAuthManagePinResponse> => {

  return customFetch<getApiAuthManagePinResponse>(getGetApiAuthManagePinUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAuthManagePinQueryKey = () => {
    return [
    'api','auth','manage','pin'
    ] as const;
    }


export const getGetApiAuthManagePinQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthManagePin>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthManagePin>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetApiAuthManagePinQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthManagePin>>> = ({ signal }) => getApiAuthManagePin({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthManagePin>>, TError, TData>
}

export type GetApiAuthManagePinQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthManagePin>>>
export type GetApiAuthManagePinQueryError = void



export function useGetApiAuthManagePin<TData = Awaited<ReturnType<typeof getApiAuthManagePin>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthManagePin>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthManagePinQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type postApiAuthManagePinResponse200 = {
  data: void
  status: 200
}

export type postApiAuthManagePinResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiAuthManagePinResponse404 = {
  data: void
  status: 404
}

export type postApiAuthManagePinResponseSuccess = (postApiAuthManagePinResponse200) & {
  headers: Headers;
};
export type postApiAuthManagePinResponseError = (postApiAuthManagePinResponse400 | postApiAuthManagePinResponse404) & {
  headers: Headers;
};

export type postApiAuthManagePinResponse = (postApiAuthManagePinResponseSuccess | postApiAuthManagePinResponseError)

export const getPostApiAuthManagePinUrl = () => {




  return `/api/auth/manage/pin`
}

export const postApiAuthManagePin = async (updatePinRequest: UpdatePinRequest, options?: Parameters<typeof customFetch>[1]): Promise<postApiAuthManagePinResponse> => {

  return customFetch<postApiAuthManagePinResponse>(getPostApiAuthManagePinUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePinRequest)
  }
);}





export const getPostApiAuthManagePinMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManagePin>>, TError,{data: UpdatePinRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManagePin>>, TError,{data: UpdatePinRequest}, TContext> => {

const mutationKey = ['postApiAuthManagePin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthManagePin>>, {data: UpdatePinRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthManagePin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthManagePinMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthManagePin>>>
    export type PostApiAuthManagePinMutationBody = UpdatePinRequest
    export type PostApiAuthManagePinMutationError = HttpValidationProblemDetails | void

    export const usePostApiAuthManagePin = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManagePin>>, TError,{data: UpdatePinRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthManagePin>>,
        TError,
        {data: UpdatePinRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthManagePinMutationOptions(options), queryClient);
    }

export type getApiPluginsUiResponse200 = {
  data: PluginUiManifestResponse[]
  status: 200
}

export type getApiPluginsUiResponseSuccess = (getApiPluginsUiResponse200) & {
  headers: Headers;
};
;

export type getApiPluginsUiResponse = (getApiPluginsUiResponseSuccess)

export const getGetApiPluginsUiUrl = () => {




  return `/api/plugins/ui`
}

export const getApiPluginsUi = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiPluginsUiResponse> => {

  return customFetch<getApiPluginsUiResponse>(getGetApiPluginsUiUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiPluginsUiQueryKey = () => {
    return [
    'api','plugins','ui'
    ] as const;
    }


export const getGetApiPluginsUiQueryOptions = <TData = Awaited<ReturnType<typeof getApiPluginsUi>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPluginsUi>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetApiPluginsUiQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPluginsUi>>> = ({ signal }) => getApiPluginsUi({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPluginsUi>>, TError, TData>
}

export type GetApiPluginsUiQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPluginsUi>>>
export type GetApiPluginsUiQueryError = unknown



export function useGetApiPluginsUi<TData = Awaited<ReturnType<typeof getApiPluginsUi>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPluginsUi>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPluginsUiQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type getApiPluginsEventsResponse200 = {
  data: string
  status: 200
}

export type getApiPluginsEventsResponseSuccess = (getApiPluginsEventsResponse200) & {
  headers: Headers;
};
;

export type getApiPluginsEventsResponse = (getApiPluginsEventsResponseSuccess)

export const getGetApiPluginsEventsUrl = () => {




  return `/api/plugins/events`
}

export const getApiPluginsEvents = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiPluginsEventsResponse> => {

  return customFetch<getApiPluginsEventsResponse>(getGetApiPluginsEventsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiPluginsEventsQueryKey = () => {
    return [
    'api','plugins','events'
    ] as const;
    }


export const getGetApiPluginsEventsQueryOptions = <TData = Awaited<ReturnType<typeof getApiPluginsEvents>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPluginsEvents>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetApiPluginsEventsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPluginsEvents>>> = ({ signal }) => getApiPluginsEvents({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPluginsEvents>>, TError, TData>
}

export type GetApiPluginsEventsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPluginsEvents>>>
export type GetApiPluginsEventsQueryError = unknown



export function useGetApiPluginsEvents<TData = Awaited<ReturnType<typeof getApiPluginsEvents>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPluginsEvents>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPluginsEventsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type postEamuseModelModuleMethodResponse200 = {
  data: void
  status: 200
}

export type postEamuseModelModuleMethodResponseSuccess = (postEamuseModelModuleMethodResponse200) & {
  headers: Headers;
};
;

export type postEamuseModelModuleMethodResponse = (postEamuseModelModuleMethodResponseSuccess)

export const getPostEamuseModelModuleMethodUrl = (model: string,
    module: string,
    method: string,) => {




  return `/eamuse/${model}/${module}/${method}`
}

export const postEamuseModelModuleMethod = async (model: string,
    module: string,
    method: string, options?: Parameters<typeof customFetch>[1]): Promise<postEamuseModelModuleMethodResponse> => {

  return customFetch<postEamuseModelModuleMethodResponse>(getPostEamuseModelModuleMethodUrl(model,module,method),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostEamuseModelModuleMethodMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEamuseModelModuleMethod>>, TError,{model: string;module: string;method: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postEamuseModelModuleMethod>>, TError,{model: string;module: string;method: string}, TContext> => {

const mutationKey = ['postEamuseModelModuleMethod'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postEamuseModelModuleMethod>>, {model: string;module: string;method: string}> = (props) => {
          const {model,module,method} = props ?? {};

          return  postEamuseModelModuleMethod(model,module,method,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostEamuseModelModuleMethodMutationResult = NonNullable<Awaited<ReturnType<typeof postEamuseModelModuleMethod>>>

    export type PostEamuseModelModuleMethodMutationError = unknown

    export const usePostEamuseModelModuleMethod = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEamuseModelModuleMethod>>, TError,{model: string;module: string;method: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postEamuseModelModuleMethod>>,
        TError,
        {model: string;module: string;method: string},
        TContext
      > => {
      return useMutation(getPostEamuseModelModuleMethodMutationOptions(options), queryClient);
    }

export type postEamuseMResponse200 = {
  data: void
  status: 200
}

export type postEamuseMResponseSuccess = (postEamuseMResponse200) & {
  headers: Headers;
};
;

export type postEamuseMResponse = (postEamuseMResponseSuccess)

export const getPostEamuseMUrl = (m: string,
    params: PostEamuseMParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/eamuse/${m}?${stringifiedParams}` : `/eamuse/${m}`
}

export const postEamuseM = async (m: string,
    params: PostEamuseMParams, options?: Parameters<typeof customFetch>[1]): Promise<postEamuseMResponse> => {

  return customFetch<postEamuseMResponse>(getPostEamuseMUrl(m,params),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostEamuseMMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEamuseM>>, TError,{m: string;params: PostEamuseMParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postEamuseM>>, TError,{m: string;params: PostEamuseMParams}, TContext> => {

const mutationKey = ['postEamuseM'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postEamuseM>>, {m: string;params: PostEamuseMParams}> = (props) => {
          const {m,params} = props ?? {};

          return  postEamuseM(m,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostEamuseMMutationResult = NonNullable<Awaited<ReturnType<typeof postEamuseM>>>

    export type PostEamuseMMutationError = unknown

    export const usePostEamuseM = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEamuseM>>, TError,{m: string;params: PostEamuseMParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postEamuseM>>,
        TError,
        {m: string;params: PostEamuseMParams},
        TContext
      > => {
      return useMutation(getPostEamuseMMutationOptions(options), queryClient);
    }

export type postEamuseResponse200 = {
  data: void
  status: 200
}

export type postEamuseResponseSuccess = (postEamuseResponse200) & {
  headers: Headers;
};
;

export type postEamuseResponse = (postEamuseResponseSuccess)

export const getPostEamuseUrl = (params: PostEamuseParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/eamuse?${stringifiedParams}` : `/eamuse`
}

export const postEamuse = async (params: PostEamuseParams, options?: Parameters<typeof customFetch>[1]): Promise<postEamuseResponse> => {

  return customFetch<postEamuseResponse>(getPostEamuseUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostEamuseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEamuse>>, TError,{params: PostEamuseParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postEamuse>>, TError,{params: PostEamuseParams}, TContext> => {

const mutationKey = ['postEamuse'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postEamuse>>, {params: PostEamuseParams}> = (props) => {
          const {params} = props ?? {};

          return  postEamuse(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostEamuseMutationResult = NonNullable<Awaited<ReturnType<typeof postEamuse>>>

    export type PostEamuseMutationError = unknown

    export const usePostEamuse = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEamuse>>, TError,{params: PostEamuseParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postEamuse>>,
        TError,
        {params: PostEamuseParams},
        TContext
      > => {
      return useMutation(getPostEamuseMutationOptions(options), queryClient);
    }
