/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Server | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  toValue,
  unref
} from 'vue';
import type {
  MaybeRefOrGetter
} from 'vue';

import type {
  AccessTokenResponse,
  CardDto,
  Claim,
  ForgotPasswordRequest,
  HttpValidationProblemDetails,
  InfoRequest,
  InfoResponse,
  LoginRequest,
  MapIdentityApiApiAuthConfirmEmailParams,
  PostApiAuthLoginParams,
  PostEamuseMParams,
  PostEamuseParams,
  RefreshRequest,
  RegisterRequest,
  ResendConfirmationEmailRequest,
  ResetPasswordRequest,
  TwoFactorRequest,
  TwoFactorResponse,
  ValidateCardRequest,
  ValidateCardResponse
} from '../types/api';

export type postApiCardsValidateResponse200 = {
  data: ValidateCardResponse
  status: 200
}

export type postApiCardsValidateResponseSuccess = (postApiCardsValidateResponse200) & {
  headers: Headers;
};
;

export type postApiCardsValidateResponse = (postApiCardsValidateResponseSuccess)

export const getPostApiCardsValidateUrl = () => {




  return `/api/cards/validate`
}

export const postApiCardsValidate = async (validateCardRequest: ValidateCardRequest, options?: RequestInit): Promise<postApiCardsValidateResponse> => {

  const res = await fetch(getPostApiCardsValidateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(validateCardRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiCardsValidateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiCardsValidateResponse
}





export const getPostApiCardsValidateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCardsValidate>>, TError,{data: ValidateCardRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiCardsValidate>>, TError,{data: ValidateCardRequest}, TContext> => {

const mutationKey = ['postApiCardsValidate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCardsValidate>>, {data: ValidateCardRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiCardsValidate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiCardsValidateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCardsValidate>>>
    export type PostApiCardsValidateMutationBody = ValidateCardRequest
    export type PostApiCardsValidateMutationError = unknown

    export const usePostApiCardsValidate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCardsValidate>>, TError,{data: ValidateCardRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiCardsValidate>>,
        TError,
        {data: ValidateCardRequest},
        TContext
      > => {
      return useMutation(getPostApiCardsValidateMutationOptions(options), queryClient);
    }

export type getApiCardsMyResponse200 = {
  data: CardDto[]
  status: 200
}

export type getApiCardsMyResponseSuccess = (getApiCardsMyResponse200) & {
  headers: Headers;
};
;

export type getApiCardsMyResponse = (getApiCardsMyResponseSuccess)

export const getGetApiCardsMyUrl = () => {




  return `/api/cards/my`
}

export const getApiCardsMy = async ( options?: RequestInit): Promise<getApiCardsMyResponse> => {

  const res = await fetch(getGetApiCardsMyUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiCardsMyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiCardsMyResponse
}





export const getGetApiCardsMyQueryKey = () => {
    return [
    'api','cards','my'
    ] as const;
    }


export const getGetApiCardsMyQueryOptions = <TData = Awaited<ReturnType<typeof getApiCardsMy>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCardsMy>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getGetApiCardsMyQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCardsMy>>> = ({ signal }) => getApiCardsMy({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCardsMy>>, TError, TData>
}

export type GetApiCardsMyQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCardsMy>>>
export type GetApiCardsMyQueryError = unknown



export function useGetApiCardsMy<TData = Awaited<ReturnType<typeof getApiCardsMy>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCardsMy>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCardsMyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type getApiUserClaimsResponse200 = {
  data: Claim[]
  status: 200
}

export type getApiUserClaimsResponseSuccess = (getApiUserClaimsResponse200) & {
  headers: Headers;
};
;

export type getApiUserClaimsResponse = (getApiUserClaimsResponseSuccess)

export const getGetApiUserClaimsUrl = () => {




  return `/api/user/claims`
}

export const getApiUserClaims = async ( options?: RequestInit): Promise<getApiUserClaimsResponse> => {

  const res = await fetch(getGetApiUserClaimsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiUserClaimsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiUserClaimsResponse
}





export const getGetApiUserClaimsQueryKey = () => {
    return [
    'api','user','claims'
    ] as const;
    }


export const getGetApiUserClaimsQueryOptions = <TData = Awaited<ReturnType<typeof getApiUserClaims>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserClaims>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getGetApiUserClaimsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUserClaims>>> = ({ signal }) => getApiUserClaims({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUserClaims>>, TError, TData>
}

export type GetApiUserClaimsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUserClaims>>>
export type GetApiUserClaimsQueryError = unknown



export function useGetApiUserClaims<TData = Awaited<ReturnType<typeof getApiUserClaims>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserClaims>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUserClaimsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type postApiAuthRegisterResponse200 = {
  data: void
  status: 200
}

export type postApiAuthRegisterResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiAuthRegisterResponseSuccess = (postApiAuthRegisterResponse200) & {
  headers: Headers;
};
export type postApiAuthRegisterResponseError = (postApiAuthRegisterResponse400) & {
  headers: Headers;
};

export type postApiAuthRegisterResponse = (postApiAuthRegisterResponseSuccess | postApiAuthRegisterResponseError)

export const getPostApiAuthRegisterUrl = () => {




  return `/api/auth/register`
}

export const postApiAuthRegister = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<postApiAuthRegisterResponse> => {

  const res = await fetch(getPostApiAuthRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiAuthRegisterResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiAuthRegisterResponse
}





export const getPostApiAuthRegisterMutationOptions = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data: RegisterRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['postApiAuthRegister'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRegister>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRegister(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRegister>>>
    export type PostApiAuthRegisterMutationBody = RegisterRequest
    export type PostApiAuthRegisterMutationError = HttpValidationProblemDetails

    export const usePostApiAuthRegister = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data: RegisterRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthRegister>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthRegisterMutationOptions(options), queryClient);
    }

export type postApiAuthLoginResponse200 = {
  data: AccessTokenResponse
  status: 200
}

export type postApiAuthLoginResponseSuccess = (postApiAuthLoginResponse200) & {
  headers: Headers;
};
;

export type postApiAuthLoginResponse = (postApiAuthLoginResponseSuccess)

export const getPostApiAuthLoginUrl = (params?: PostApiAuthLoginParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/login?${stringifiedParams}` : `/api/auth/login`
}

export const postApiAuthLogin = async (loginRequest: LoginRequest,
    params?: PostApiAuthLoginParams, options?: RequestInit): Promise<postApiAuthLoginResponse> => {

  const res = await fetch(getPostApiAuthLoginUrl(params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiAuthLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAuthLoginResponse
}





export const getPostApiAuthLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: LoginRequest;params?: PostApiAuthLoginParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: LoginRequest;params?: PostApiAuthLoginParams}, TContext> => {

const mutationKey = ['postApiAuthLogin'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthLogin>>, {data: LoginRequest;params?: PostApiAuthLoginParams}> = (props) => {
          const {data,params} = props ?? {};

          return  postApiAuthLogin(data,params,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogin>>>
    export type PostApiAuthLoginMutationBody = LoginRequest
    export type PostApiAuthLoginMutationError = unknown

    export const usePostApiAuthLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: LoginRequest;params?: PostApiAuthLoginParams}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthLogin>>,
        TError,
        {data: LoginRequest;params?: PostApiAuthLoginParams},
        TContext
      > => {
      return useMutation(getPostApiAuthLoginMutationOptions(options), queryClient);
    }

export type postApiAuthRefreshResponse200 = {
  data: AccessTokenResponse
  status: 200
}

export type postApiAuthRefreshResponseSuccess = (postApiAuthRefreshResponse200) & {
  headers: Headers;
};
;

export type postApiAuthRefreshResponse = (postApiAuthRefreshResponseSuccess)

export const getPostApiAuthRefreshUrl = () => {




  return `/api/auth/refresh`
}

export const postApiAuthRefresh = async (refreshRequest: RefreshRequest, options?: RequestInit): Promise<postApiAuthRefreshResponse> => {

  const res = await fetch(getPostApiAuthRefreshUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(refreshRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiAuthRefreshResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAuthRefreshResponse
}





export const getPostApiAuthRefreshMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,{data: RefreshRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,{data: RefreshRequest}, TContext> => {

const mutationKey = ['postApiAuthRefresh'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRefresh>>, {data: RefreshRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRefresh(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRefresh>>>
    export type PostApiAuthRefreshMutationBody = RefreshRequest
    export type PostApiAuthRefreshMutationError = unknown

    export const usePostApiAuthRefresh = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,{data: RefreshRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthRefresh>>,
        TError,
        {data: RefreshRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthRefreshMutationOptions(options), queryClient);
    }

export type mapIdentityApiApiAuthConfirmEmailResponse200 = {
  data: void
  status: 200
}

export type mapIdentityApiApiAuthConfirmEmailResponseSuccess = (mapIdentityApiApiAuthConfirmEmailResponse200) & {
  headers: Headers;
};
;

export type mapIdentityApiApiAuthConfirmEmailResponse = (mapIdentityApiApiAuthConfirmEmailResponseSuccess)

export const getMapIdentityApiApiAuthConfirmEmailUrl = (params: MapIdentityApiApiAuthConfirmEmailParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/confirmEmail?${stringifiedParams}` : `/api/auth/confirmEmail`
}

export const mapIdentityApiApiAuthConfirmEmail = async (params: MapIdentityApiApiAuthConfirmEmailParams, options?: RequestInit): Promise<mapIdentityApiApiAuthConfirmEmailResponse> => {

  const res = await fetch(getMapIdentityApiApiAuthConfirmEmailUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: mapIdentityApiApiAuthConfirmEmailResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as mapIdentityApiApiAuthConfirmEmailResponse
}





export const getMapIdentityApiApiAuthConfirmEmailQueryKey = (params?: MaybeRefOrGetter<MapIdentityApiApiAuthConfirmEmailParams>,) => {
    return [
    'api','auth','confirmEmail', ...(params ? [params] : [])
    ] as const;
    }


export const getMapIdentityApiApiAuthConfirmEmailQueryOptions = <TData = Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>, TError = unknown>(params: MaybeRefOrGetter<MapIdentityApiApiAuthConfirmEmailParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getMapIdentityApiApiAuthConfirmEmailQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>> = ({ signal }) => mapIdentityApiApiAuthConfirmEmail(toValue(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>, TError, TData>
}

export type MapIdentityApiApiAuthConfirmEmailQueryResult = NonNullable<Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>>
export type MapIdentityApiApiAuthConfirmEmailQueryError = unknown



export function useMapIdentityApiApiAuthConfirmEmail<TData = Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>, TError = unknown>(
 params: MaybeRefOrGetter<MapIdentityApiApiAuthConfirmEmailParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMapIdentityApiApiAuthConfirmEmailQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type postApiAuthResendConfirmationEmailResponse200 = {
  data: void
  status: 200
}

export type postApiAuthResendConfirmationEmailResponseSuccess = (postApiAuthResendConfirmationEmailResponse200) & {
  headers: Headers;
};
;

export type postApiAuthResendConfirmationEmailResponse = (postApiAuthResendConfirmationEmailResponseSuccess)

export const getPostApiAuthResendConfirmationEmailUrl = () => {




  return `/api/auth/resendConfirmationEmail`
}

export const postApiAuthResendConfirmationEmail = async (resendConfirmationEmailRequest: ResendConfirmationEmailRequest, options?: RequestInit): Promise<postApiAuthResendConfirmationEmailResponse> => {

  const res = await fetch(getPostApiAuthResendConfirmationEmailUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(resendConfirmationEmailRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiAuthResendConfirmationEmailResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiAuthResendConfirmationEmailResponse
}





export const getPostApiAuthResendConfirmationEmailMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>, TError,{data: ResendConfirmationEmailRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>, TError,{data: ResendConfirmationEmailRequest}, TContext> => {

const mutationKey = ['postApiAuthResendConfirmationEmail'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>, {data: ResendConfirmationEmailRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthResendConfirmationEmail(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthResendConfirmationEmailMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>>
    export type PostApiAuthResendConfirmationEmailMutationBody = ResendConfirmationEmailRequest
    export type PostApiAuthResendConfirmationEmailMutationError = unknown

    export const usePostApiAuthResendConfirmationEmail = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>, TError,{data: ResendConfirmationEmailRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>,
        TError,
        {data: ResendConfirmationEmailRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthResendConfirmationEmailMutationOptions(options), queryClient);
    }

export type postApiAuthForgotPasswordResponse200 = {
  data: void
  status: 200
}

export type postApiAuthForgotPasswordResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiAuthForgotPasswordResponseSuccess = (postApiAuthForgotPasswordResponse200) & {
  headers: Headers;
};
export type postApiAuthForgotPasswordResponseError = (postApiAuthForgotPasswordResponse400) & {
  headers: Headers;
};

export type postApiAuthForgotPasswordResponse = (postApiAuthForgotPasswordResponseSuccess | postApiAuthForgotPasswordResponseError)

export const getPostApiAuthForgotPasswordUrl = () => {




  return `/api/auth/forgotPassword`
}

export const postApiAuthForgotPassword = async (forgotPasswordRequest: ForgotPasswordRequest, options?: RequestInit): Promise<postApiAuthForgotPasswordResponse> => {

  const res = await fetch(getPostApiAuthForgotPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(forgotPasswordRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiAuthForgotPasswordResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiAuthForgotPasswordResponse
}





export const getPostApiAuthForgotPasswordMutationOptions = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthForgotPassword>>, TError,{data: ForgotPasswordRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthForgotPassword>>, TError,{data: ForgotPasswordRequest}, TContext> => {

const mutationKey = ['postApiAuthForgotPassword'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthForgotPassword>>, {data: ForgotPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthForgotPassword(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthForgotPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthForgotPassword>>>
    export type PostApiAuthForgotPasswordMutationBody = ForgotPasswordRequest
    export type PostApiAuthForgotPasswordMutationError = HttpValidationProblemDetails

    export const usePostApiAuthForgotPassword = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthForgotPassword>>, TError,{data: ForgotPasswordRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthForgotPassword>>,
        TError,
        {data: ForgotPasswordRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthForgotPasswordMutationOptions(options), queryClient);
    }

export type postApiAuthResetPasswordResponse200 = {
  data: void
  status: 200
}

export type postApiAuthResetPasswordResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiAuthResetPasswordResponseSuccess = (postApiAuthResetPasswordResponse200) & {
  headers: Headers;
};
export type postApiAuthResetPasswordResponseError = (postApiAuthResetPasswordResponse400) & {
  headers: Headers;
};

export type postApiAuthResetPasswordResponse = (postApiAuthResetPasswordResponseSuccess | postApiAuthResetPasswordResponseError)

export const getPostApiAuthResetPasswordUrl = () => {




  return `/api/auth/resetPassword`
}

export const postApiAuthResetPassword = async (resetPasswordRequest: ResetPasswordRequest, options?: RequestInit): Promise<postApiAuthResetPasswordResponse> => {

  const res = await fetch(getPostApiAuthResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(resetPasswordRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiAuthResetPasswordResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiAuthResetPasswordResponse
}





export const getPostApiAuthResetPasswordMutationOptions = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResetPassword>>, TError,{data: ResetPasswordRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResetPassword>>, TError,{data: ResetPasswordRequest}, TContext> => {

const mutationKey = ['postApiAuthResetPassword'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthResetPassword>>, {data: ResetPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthResetPassword(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthResetPassword>>>
    export type PostApiAuthResetPasswordMutationBody = ResetPasswordRequest
    export type PostApiAuthResetPasswordMutationError = HttpValidationProblemDetails

    export const usePostApiAuthResetPassword = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResetPassword>>, TError,{data: ResetPasswordRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthResetPassword>>,
        TError,
        {data: ResetPasswordRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthResetPasswordMutationOptions(options), queryClient);
    }

export type postApiAuthManage2faResponse200 = {
  data: TwoFactorResponse
  status: 200
}

export type postApiAuthManage2faResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiAuthManage2faResponse404 = {
  data: void
  status: 404
}

export type postApiAuthManage2faResponseSuccess = (postApiAuthManage2faResponse200) & {
  headers: Headers;
};
export type postApiAuthManage2faResponseError = (postApiAuthManage2faResponse400 | postApiAuthManage2faResponse404) & {
  headers: Headers;
};

export type postApiAuthManage2faResponse = (postApiAuthManage2faResponseSuccess | postApiAuthManage2faResponseError)

export const getPostApiAuthManage2faUrl = () => {




  return `/api/auth/manage/2fa`
}

export const postApiAuthManage2fa = async (twoFactorRequest: TwoFactorRequest, options?: RequestInit): Promise<postApiAuthManage2faResponse> => {

  const res = await fetch(getPostApiAuthManage2faUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(twoFactorRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiAuthManage2faResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAuthManage2faResponse
}





export const getPostApiAuthManage2faMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManage2fa>>, TError,{data: TwoFactorRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManage2fa>>, TError,{data: TwoFactorRequest}, TContext> => {

const mutationKey = ['postApiAuthManage2fa'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthManage2fa>>, {data: TwoFactorRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthManage2fa(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthManage2faMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthManage2fa>>>
    export type PostApiAuthManage2faMutationBody = TwoFactorRequest
    export type PostApiAuthManage2faMutationError = HttpValidationProblemDetails | void

    export const usePostApiAuthManage2fa = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManage2fa>>, TError,{data: TwoFactorRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthManage2fa>>,
        TError,
        {data: TwoFactorRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthManage2faMutationOptions(options), queryClient);
    }

export type getApiAuthManageInfoResponse200 = {
  data: InfoResponse
  status: 200
}

export type getApiAuthManageInfoResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type getApiAuthManageInfoResponse404 = {
  data: void
  status: 404
}

export type getApiAuthManageInfoResponseSuccess = (getApiAuthManageInfoResponse200) & {
  headers: Headers;
};
export type getApiAuthManageInfoResponseError = (getApiAuthManageInfoResponse400 | getApiAuthManageInfoResponse404) & {
  headers: Headers;
};

export type getApiAuthManageInfoResponse = (getApiAuthManageInfoResponseSuccess | getApiAuthManageInfoResponseError)

export const getGetApiAuthManageInfoUrl = () => {




  return `/api/auth/manage/info`
}

export const getApiAuthManageInfo = async ( options?: RequestInit): Promise<getApiAuthManageInfoResponse> => {

  const res = await fetch(getGetApiAuthManageInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiAuthManageInfoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAuthManageInfoResponse
}





export const getGetApiAuthManageInfoQueryKey = () => {
    return [
    'api','auth','manage','info'
    ] as const;
    }


export const getGetApiAuthManageInfoQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthManageInfo>>, TError = HttpValidationProblemDetails | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthManageInfo>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getGetApiAuthManageInfoQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthManageInfo>>> = ({ signal }) => getApiAuthManageInfo({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthManageInfo>>, TError, TData>
}

export type GetApiAuthManageInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthManageInfo>>>
export type GetApiAuthManageInfoQueryError = HttpValidationProblemDetails | void



export function useGetApiAuthManageInfo<TData = Awaited<ReturnType<typeof getApiAuthManageInfo>>, TError = HttpValidationProblemDetails | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthManageInfo>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthManageInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type postApiAuthManageInfoResponse200 = {
  data: InfoResponse
  status: 200
}

export type postApiAuthManageInfoResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiAuthManageInfoResponse404 = {
  data: void
  status: 404
}

export type postApiAuthManageInfoResponseSuccess = (postApiAuthManageInfoResponse200) & {
  headers: Headers;
};
export type postApiAuthManageInfoResponseError = (postApiAuthManageInfoResponse400 | postApiAuthManageInfoResponse404) & {
  headers: Headers;
};

export type postApiAuthManageInfoResponse = (postApiAuthManageInfoResponseSuccess | postApiAuthManageInfoResponseError)

export const getPostApiAuthManageInfoUrl = () => {




  return `/api/auth/manage/info`
}

export const postApiAuthManageInfo = async (infoRequest: InfoRequest, options?: RequestInit): Promise<postApiAuthManageInfoResponse> => {

  const res = await fetch(getPostApiAuthManageInfoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(infoRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiAuthManageInfoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAuthManageInfoResponse
}





export const getPostApiAuthManageInfoMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManageInfo>>, TError,{data: InfoRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManageInfo>>, TError,{data: InfoRequest}, TContext> => {

const mutationKey = ['postApiAuthManageInfo'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthManageInfo>>, {data: InfoRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthManageInfo(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthManageInfoMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthManageInfo>>>
    export type PostApiAuthManageInfoMutationBody = InfoRequest
    export type PostApiAuthManageInfoMutationError = HttpValidationProblemDetails | void

    export const usePostApiAuthManageInfo = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthManageInfo>>, TError,{data: InfoRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postApiAuthManageInfo>>,
        TError,
        {data: InfoRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthManageInfoMutationOptions(options), queryClient);
    }

export type postEamuseModelModuleMethodResponse200 = {
  data: void
  status: 200
}

export type postEamuseModelModuleMethodResponseSuccess = (postEamuseModelModuleMethodResponse200) & {
  headers: Headers;
};
;

export type postEamuseModelModuleMethodResponse = (postEamuseModelModuleMethodResponseSuccess)

export const getPostEamuseModelModuleMethodUrl = (model: string,
    module: string,
    method: string,) => {




  return `/eamuse/${model}/${module}/${method}`
}

export const postEamuseModelModuleMethod = async (model: string,
    module: string,
    method: string, options?: RequestInit): Promise<postEamuseModelModuleMethodResponse> => {

  const res = await fetch(getPostEamuseModelModuleMethodUrl(model,module,method),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postEamuseModelModuleMethodResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postEamuseModelModuleMethodResponse
}





export const getPostEamuseModelModuleMethodMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEamuseModelModuleMethod>>, TError,{model: string;module: string;method: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postEamuseModelModuleMethod>>, TError,{model: string;module: string;method: string}, TContext> => {

const mutationKey = ['postEamuseModelModuleMethod'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postEamuseModelModuleMethod>>, {model: string;module: string;method: string}> = (props) => {
          const {model,module,method} = props ?? {};

          return  postEamuseModelModuleMethod(model,module,method,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostEamuseModelModuleMethodMutationResult = NonNullable<Awaited<ReturnType<typeof postEamuseModelModuleMethod>>>

    export type PostEamuseModelModuleMethodMutationError = unknown

    export const usePostEamuseModelModuleMethod = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEamuseModelModuleMethod>>, TError,{model: string;module: string;method: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postEamuseModelModuleMethod>>,
        TError,
        {model: string;module: string;method: string},
        TContext
      > => {
      return useMutation(getPostEamuseModelModuleMethodMutationOptions(options), queryClient);
    }

export type postEamuseMResponse200 = {
  data: void
  status: 200
}

export type postEamuseMResponseSuccess = (postEamuseMResponse200) & {
  headers: Headers;
};
;

export type postEamuseMResponse = (postEamuseMResponseSuccess)

export const getPostEamuseMUrl = (m: string,
    params: PostEamuseMParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/eamuse/${m}?${stringifiedParams}` : `/eamuse/${m}`
}

export const postEamuseM = async (m: string,
    params: PostEamuseMParams, options?: RequestInit): Promise<postEamuseMResponse> => {

  const res = await fetch(getPostEamuseMUrl(m,params),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postEamuseMResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postEamuseMResponse
}





export const getPostEamuseMMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEamuseM>>, TError,{m: string;params: PostEamuseMParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postEamuseM>>, TError,{m: string;params: PostEamuseMParams}, TContext> => {

const mutationKey = ['postEamuseM'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postEamuseM>>, {m: string;params: PostEamuseMParams}> = (props) => {
          const {m,params} = props ?? {};

          return  postEamuseM(m,params,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostEamuseMMutationResult = NonNullable<Awaited<ReturnType<typeof postEamuseM>>>

    export type PostEamuseMMutationError = unknown

    export const usePostEamuseM = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEamuseM>>, TError,{m: string;params: PostEamuseMParams}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postEamuseM>>,
        TError,
        {m: string;params: PostEamuseMParams},
        TContext
      > => {
      return useMutation(getPostEamuseMMutationOptions(options), queryClient);
    }

export type postEamuseResponse200 = {
  data: void
  status: 200
}

export type postEamuseResponseSuccess = (postEamuseResponse200) & {
  headers: Headers;
};
;

export type postEamuseResponse = (postEamuseResponseSuccess)

export const getPostEamuseUrl = (params: PostEamuseParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/eamuse?${stringifiedParams}` : `/eamuse`
}

export const postEamuse = async (params: PostEamuseParams, options?: RequestInit): Promise<postEamuseResponse> => {

  const res = await fetch(getPostEamuseUrl(params),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postEamuseResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postEamuseResponse
}





export const getPostEamuseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEamuse>>, TError,{params: PostEamuseParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postEamuse>>, TError,{params: PostEamuseParams}, TContext> => {

const mutationKey = ['postEamuse'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postEamuse>>, {params: PostEamuseParams}> = (props) => {
          const {params} = props ?? {};

          return  postEamuse(params,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostEamuseMutationResult = NonNullable<Awaited<ReturnType<typeof postEamuse>>>

    export type PostEamuseMutationError = unknown

    export const usePostEamuse = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEamuse>>, TError,{params: PostEamuseParams}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postEamuse>>,
        TError,
        {params: PostEamuseParams},
        TContext
      > => {
      return useMutation(getPostEamuseMutationOptions(options), queryClient);
    }
