/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CardDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  konamiId?: string;
  rawId?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  userId?: number | string;
}
