/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ClaimProperties } from './claimProperties';
import type { ClaimsIdentity } from './claimsIdentity';

export interface Claim {
  /** @nullable */
  issuer?: string | null;
  /** @nullable */
  originalIssuer?: string | null;
  /** @nullable */
  properties?: ClaimProperties;
  subject?: ClaimsIdentity;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  value?: string | null;
  /** @nullable */
  valueType?: string | null;
}
