/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Claim } from './claim';

export interface ClaimsIdentity {
  /** @nullable */
  authenticationType?: string | null;
  isAuthenticated?: boolean;
  actor?: null | ClaimsIdentity;
  bootstrapContext?: unknown;
  /** @nullable */
  claims?: Claim[] | null;
  /** @nullable */
  label?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  nameClaimType?: string | null;
  /** @nullable */
  roleClaimType?: string | null;
}
