/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PluginNavItem } from './pluginNavItem';
import type { PluginRoute } from './pluginRoute';

export interface PluginUiManifestResponse {
  pluginId: string;
  displayName: string;
  icon: string;
  bundleUrl: string;
  /** @nullable */
  sri: string | null;
  navItems: PluginNavItem[];
  routes: PluginRoute[];
}
