/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Server | v1
 * OpenAPI spec version: 1.0.0
 */

export type PostApiAuthLoginParams = {
useCookies?: boolean;
useSessionCookies?: boolean;
};
